### 1. 유저 생성 - 김민철
POST http://localhost:8080/openapi-transaction/api/user/create/v1
Content-Type: application/json

{
    "name": "김민철"
}

### 2. 계좌 생성
POST http://localhost:8080/openapi-transaction/api/kcd-bank/account-create/v1
Content-Type: application/json

{
  "accountNumber": "123-4567-890",
  "userId": 1,
  "amount": 0
}


### 3. 사업자 송금 요청 생성
POST http://localhost:8080/openapi-transaction/api/biz-remit-request/v1
Content-Type: application/json

{
  "bankTransactionId": "123-4567-890",
  "userId": 1,
  "userKcdBankAccountId": 1,
  "requestDate" : "2024-04-08T00:00:00",
  "fromAccountId": "BizBankAccount A",
  "toAccountId": "BizBankAccount B",
  "amount": 1000
}

### 4. 사업자 은행 계좌에서 KCD 은행 계좌 이체
POST http://localhost:8080/openapi-transaction/api/biz-remit-request/v1/1/account-deposit
Content-Type: application/json

{
  "bankTransactionId": "123-4567-890",
  "userId": 1,
  "userKcdBankAccountId": 1,
  "requestDate" : "2024-04-08T00:00:00",
  "fromAccountId": "BizBankAccount A",
  "toAccountId": "BizBankAccount B",
  "amount": 1000
}

### 5. KCD 은행 계좌에서 사업자 은행 계좌 이체
POST http://localhost:8080/openapi-transaction/api/biz-remit-request/v1/1/account-withdrawal
Content-Type: application/json

{
  "bankTransactionId": "123-4567-890",
  "userId": 1,
  "userKcdBankAccountId": 1,
  "requestDate" : "2024-04-08T00:00:00",
  "fromAccountId": "BizBankAccount A",
  "toAccountId": "BizBankAccount B",
  "amount": 1000
}