spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sandbox?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF8&connectTimeout=5000&socketTimeout=120000&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
#logging:
#  level:
#    root: DEBUG

aimhigh:
  openapi:
    transaction:
      isMockingMode: true